### ISSUE TITLE
Error loading extension in Burp Suite 1.7.18 (Jython 2.7.0 on Windows 7)

### ISSUE THREAD

**Issue by ap00rv** [SecurityInnovation/AuthMatrix#29]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: (22, 'Invalid argument', 'E:\\Users\\*************\\AppData\\Roaming\\BurpSuite\x08apps\x18d8ee9f40c041b0bfec67441aad158e')

	at org.python.core.Py.OSError(Py.java:162)
	at org.python.modules.posix.PosixModule.absolutePath(PosixModule.java:1166)
	at org.python.modules.posix.PosixModule.chdir(PosixModule.java:289)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.pycode._pyx2.f$0(<string>:1)
	at org.python.pycode._pyx2.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.Py.exec(Py.java:1430)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at burp.n0e.<init>(Unknown Source)
	at burp.oub.a(Unknown Source)
	at burp.e4b.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by mickayz** [comment]
Thanks for reporting! This was a known issue with Burp Suite that was fixed in version 1.7.19

More information here:

http://releases.portswigger.net/2017/03/1719.html

Closing for now. If updating to 1.7.19 doesn't fix it, please re-open this issue and I'll take a look into it.

Cheers,
-Mick
