### ISSUE TITLE
No viable alternative at input 'for' error on load in to Burp

### ISSUE THREAD

**Issue by combobulify** [SecurityInnovation/AuthMatrix#66]
I am getting the following error when I try to load AuthMatrix in to Burp.  I've tried making some code changes to see if I could resolve the issue but have not succeeded yet.  Could you please have a look?  I am using Jython 2.7.0
`
SyntaxError: ("no viable alternative at input 'for'", ('C:\\Users\\****\\AppData\\Roaming\\BurpSuite\\bapps\\30d8ee9f40c041b0bfec67441aad158e\\AuthMatrix.py', 1587, 37, ''))

	at org.python.core.ParserFacade.fixParseError(ParserFacade.java:92)
	at org.python.core.ParserFacade.parse(ParserFacade.java:184)
	at org.python.core.Py.compile_flags(Py.java:1731)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:514)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.owb.<init>(Unknown Source)
	at burp.s5c.a(Unknown Source)
	at burp.zfb.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by mickayz** [comment]
This sounds like an issue with the Jython library included.  Are you using the .jar file? If not I recommend giving that a try.

http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar

**Comment by mickayz** [comment]
I will assume that this issue is jython related.  If you are still having trouble, please reopen this ticket.
