### ISSUE TITLE
Stack trace when adding first role after message

### ISSUE THREAD

**Issue by mickayz** [SecurityInnovation/AuthMatrix#8]
Repro:
1. Clear AuthMatrix state
2. Send request to AuthMatrix
3. Create New Role

Stacktrace
Traceback (most recent call last):
  File "/AuthMatrix/AuthMatrix.py", line 337, in getInputRoleClick
    self._db.getOrCreateRole(newRole)
  File "/AuthMatrix/AuthMatrix.py", line 629, in getOrCreateRole
    self.arrayOfMessages[messageIndex].addRoleByIndex(userIndex)
UnboundLocalError: local variable 'userIndex' referenced before assignment

**Comment by mickayz** [comment]
This is a major bug that affects the results and message table checkbox UI when a user adds new roles after messages have already been added.  Yikes!

Fixed in v0.5.2, commit: 16af1bd
